### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by xstana** [Wissididom/Twitch-Follows-To-Discord#17]
Hi buddy, what you did looks really great but I couldn't use it because there is no documentation, can you help me?

**Comment by Wissididom** [comment]
It's just because I hadn't expected it to be found by anyone. To run it you just need to download/clone the repo and inside that repo do:
1. Copy `example.env` to `.env` and inside the `.env` set it's values (Format `Key=Value`)
2. Run `npm i` or `npm install` to install dependencies to the `node_modules` folder
3. Run `node index.js` (I might add a start script at some point tho, so you can just do `npm start`)

At least Node 18 needs to be installed on the system.
